language: c
 
#whitelist
branches:
  only:
    - master
    
git:
  submodules: false

install:
  - sudo apt-get install mono-devel mono-gmcs cmake libboost-dev build-essential
 
script:
  - source ./alternative-lib-compile.sh
  - cd build/libfiles
  - [[ -f libSystem.a && -f libgc-lib.a ]]

notifications:
 email: true
