language: c
 
#whitelist
branches:
  only:
    - master

git:
  submodules: false
  
install:
  - sudo apt-get -f install cmake libboost-all-dev libboost-dev build-essential
  - wget http://ftp.us.debian.org/debian/pool/main/b/boost-defaults/libboost-chrono-dev_1.55.0.2_amd64.deb
  - wget http://ftp.us.debian.org/debian/pool/main/b/boost-defaults/libboost-locale-dev_1.55.0.2_amd64.deb
  - sudo dpkg -i libboost-chrono-dev_1.55.0.2_amd64.deb
  - sudo dpkg -i libboost-locale-dev_1.55.0.2_amd64.deb
  - sudo apt-get -f install
 
script:
  - mkdir tmp
  - cd tmp
  - git clone https://github.com/AlexAlbala/Alter-Native
  - cd Alter-Native/Tools
  - declare -x ALTERNATIVE_TOOLS_PATH=`pwd`
  - declare -x BOOST_LIBRARYDIR=/usr/lib/
  - cd ../../../
  - source ./alternative-lib-compile.sh
  - rm -rf tmp
  - cd build/libfiles
  - "[[ -f libSystem.a && -f libgc-lib.a ]]"

notifications:
 email: true
