language: c
 
#whitelist
branches:
  only:
    - master

git:
  submodules: false
  
install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo apt-get update -y
  - sudo apt-get install libboost1.55-all-dev -y
 
script:
  - mkdir tmp
  - cd tmp
  - git clone https://github.com/AlexAlbala/Alter-Native
  - cd Alter-Native/Tools
  - export ALTERNATIVE_TOOLS_PATH=`pwd`
  - export BOOST_LIBRARYDIR=/usr/lib/
  - cd ../../../
  - source ./alternative-lib-compile.sh
  - rm -rf tmp
  - cd build/libfiles
  - "[[ -f libSystem.a && -f libgc-lib.a ]]"

notifications:
  email: true
