language: c
 
#whitelist
branches:
  only:
    - master
    
git:
  submodules: false

install:
  - sudo apt-get install cmake libboost-all-dev build-essential
 
script:
  - mkdir tmp
  - cd tmp
  - git clone https://github.com/AlexAlbala/Alter-Native
  - cd Alter-Native/Tools
  - declare -x ALTERNATIVE_TOOLS_PATH=`pwd`
  - cd ../../../
  - source ./alternative-lib-compile.sh
  - rm -rf tmp
  - cd build/libfiles
  - "[[ -f libSystem.a && -f libgc-lib.a ]]"

notifications:
 email: true
